### ISSUE TITLE
List all regions

### ISSUE THREAD

**Issue by sts-ryan-holton** [rinvex/countries#235]
Hi, I need to get all of the regions broken down into the following categories:

- Europe
- US/Canada
- Asia/Oceania
- Middle East/Africa
- Americas

This is my current approach:

```php
// Europe
$euCountries = \Rinvex\Country\CountryLoader::where('geo.region', 'Europe');

// US/Canada
$usCountries = \Rinvex\Country\CountryLoader::where('geo.region', 'US/Canada');

// Asia/Oceania
$asiaCountries = \Rinvex\Country\CountryLoader::where('geo.region', 'Asia/Oceania');

// Middle East/Africa
$middleEastCountries = \Rinvex\Country\CountryLoader::where('geo.region', 'Middle Ease/Africa');

// Americas
$americasCountries = \Rinvex\Country\CountryLoader::where('geo.region', 'Americas');


return response()->json([
    'all_regions' => \Rinvex\Country\CountryLoader::whereNotNull('geo.region')->count(),
    'eu' => count($euCountries),
    'us' => count($usCountries),
    'aso' => count($asiaCountries),
    'mea' => count($middleEastCountries),
    'sa' => count($americasCountries)
], 200);
```

I get countries back for Europe and Americas, but not the others. I tried listing regions but nothing shows up?

**Comment by Omranic** [comment]
Thanks for your question, it’s not returning all results because you’re not calling the right region names.

Checkout data files to see the right names, for example Egypt > Africa https://github.com/rinvex/countries/blob/master/resources/data/eg.json

It might be helpful to get all countries details to see all the regions before splitting, happy coding 🙌
